# Generated by Django 4.2.16 on 2025-05-01 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0067_issue_cached_display_title_es_and_more'),
        ('submission', '9011_tuw_remove_obsolete_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('', ''), ('', 'draft'), ('findable', 'findable'), ('registered', 'registered')], max_length=20, null=True)),
                ('ts', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submission.article')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.issue')),
            ],
        ),
        migrations.CreateModel(
            name='Alma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsid', models.CharField(blank=True, max_length=50, null=True)),
                ('ac', models.CharField(blank=True, max_length=50, null=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submission.article')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.issue')),
            ],
        ),
    ]
