# Generated by Django 4.2.22 on 2025-08-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alma',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obsolete_prep_3', to='submission.article'),
        ),
        migrations.AlterField(
            model_name='alma',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obsolete_prep_4', to='journal.issue'),
        ),
        migrations.AlterField(
            model_name='datacite',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obsolete_prep_1', to='submission.article'),
        ),
        migrations.AlterField(
            model_name='datacite',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obsolete_prep_2', to='journal.issue'),
        ),
    ]
