# Generated by Django 4.2.22 on 2025-08-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_alter_alma_article_alter_alma_issue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacite',
            name='article',
        ),
        migrations.RemoveField(
            model_name='datacite',
            name='issue',
        ),
        migrations.DeleteModel(
            name='Alma',
        ),
        migrations.DeleteModel(
            name='DataCite',
        ),
    ]
