# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-16 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0008_auto_20191119_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleaccess',
            name='ip',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
