# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-10 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '9000_tuw_add_issue_str_year_vlid'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='keywords_de',
            field=models.ManyToManyField(blank=True, null=True, to='submission.KeywordDe'),
        ),
    ]
