# Generated by Django 4.2.22 on 2025-10-17 11:18

import core.file_system
from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0067_issue_cached_display_title_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='under_construction_image',
            field=models.ImageField(blank=True, help_text='Image shown for frontend when initial data input is still work in progress', null=True, storage=core.file_system.JanewayFileSystemStorage(), upload_to=journal.models.cover_images_upload_path),
        ),
    ]
