# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-06 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '9001_journal_keywords_de'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='xsl',
            field=models.ForeignKey(default=journal.models.default_xsl, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.XSLFile'),
        ),
    ]
