# Generated by Django 4.2.22 on 2025-08-14 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sync', '0002_alter_alma_article_alter_alma_issue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('', ''), ('', 'draft'), ('findable', 'findable'), ('registered', 'registered')], max_length=20, null=True)),
                ('ts', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submission.article')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.issue')),
            ],
        ),
        migrations.CreateModel(
            name='Alma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsid', models.CharField(blank=True, max_length=50, null=True)),
                ('ac', models.CharField(blank=True, max_length=50, null=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submission.article')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.issue')),
            ],
        ),
        migrations.RunSQL('INSERT INTO tuw_sync_datacite (status,ts,article_id,issue_id) SELECT status,ts,article_id,issue_id FROM sync_datacite;'),
    ]
