# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 09:17
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('identifiers', '0006_crossrefdeposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifier',
            name='id_type',
            field=models.CharField(choices=[('doi', 'DOI'), ('uri', 'URI Path'), ('pubid', 'Publisher ID'), ('urn', 'URN'), ('ac', 'AC'), ('vlid', 'VL ID')], max_length=300),
        ),
    ]
