# Generated by Django 4.2.16 on 2024-10-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_alter_accountrole_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='detected_language',
            field=models.CharField(blank=True, default=None, max_length=2, null=True, verbose_name='Detected language'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_spam',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Message is spam'),
        ),
    ]
