# Generated by Django 4.2.28 on 2026-05-26 15:19

from django.db import migrations

# TUW
# filtered constraints are not supported by mariadb
# emulate by adding an additional column, that is null, wenn ror_id = ''

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_one_click_review_on_by_default'),
    ]

    operations = [
            migrations.RunSQL(
                sql="""
                    ALTER TABLE core_organization
                    ADD COLUMN ror_id_virtual VARCHAR(10) GENERATED ALWAYS AS (
                        CASE WHEN ror_id = '' THEN NULL ELSE ror_id END
                    ) VIRTUAL;

                    ALTER TABLE core_organization
                    ADD CONSTRAINT idx_ror_id
                    UNIQUE (ror_id_virtual);
                """,
                reverse_sql="""
                    -- This handles rollbacks if you ever undo this migration
                    ALTER TABLE core_organization
                    DROP CONSTRAINT idx_ror_id;

                    ALTER TABLE core_organization 
                    DROP COLUMN ror_id_virtual;
                """
            )
        ]