# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-03 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0035_auto_20190627_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract_de',
            field=models.TextField(blank=True, help_text='Abstract (de)', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='subtitle_de',
            field=models.CharField(blank=True, help_text='Subtitle of the article display format; Title: Subtitle (de)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_de',
            field=models.CharField(blank=True, help_text='Your article title (de)', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='stage',
            field=models.CharField(choices=[('Unsubmitted', 'Unsubmitted'), ('Unassigned', 'Unassigned'), ('Assigned', 'Assigned to Editor'), ('Under Review', 'Peer Review'), ('Under Revision', 'Revision'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Editor Copyediting', 'Editor Copyediting'), ('Author Copyediting', 'Author Copyediting'), ('Final Copyediting', 'Final Copyediting'), ('Typesetting', 'Typesetting'), ('Proofing', 'Proofing'), ('pre_publication', 'Pre Publication'), ('Published', 'Published'), ('preprint_review', 'Preprint Review'), ('preprint_published', 'Preprint Published'), ('Back Content', 'Back Content Plugin')], default='Unsubmitted', max_length=200),
        ),
    ]
