# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-04 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0036_auto_20190703_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordDe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='keywords_de',
            field=models.ManyToManyField(blank=True, null=True, to='submission.KeywordDe'),
        ),
    ]
