# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-05 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0037_auto_20190704_0824'),
        ('submission', '0036_auto_20190704_1200'),
    ]

    operations = [
    ]
