# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0036_tuw_20190716_1400'),
        ('submission', '0037_tuw_20190716_1410'),
    ]

    operations = [
    ]
