# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-12 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0038_tuw_20190812_2000'),
        ('submission', '0035_auto_20190627_1331'),
    ]

    operations = [
    ]
