# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-13 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0039_tuw_20190812_2000'),
        ('submission', '0038_merge_20190812_1614'),
        ('submission', '0040_tuw_20190813_1135'),
    ]

    operations = [
    ]
