# Generated by Django 4.2.18 on 2025-02-18 11:48

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "submission",
            "9011_tuw_remove_obsolete_fields",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="jats_article_type_override",
            field=core.model_utils.DynamicChoiceField(
                blank=True,
                choices=[],
                default=None,
                help_text="The type of article as per the JATS standard. This field allows you to override the default for the section.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="jats_article_type",
            field=core.model_utils.DynamicChoiceField(
                blank=True,
                choices=[],
                help_text="The default JATS article type for articles in this section. This can be overridden on a per-article basis.",
                max_length=255,
                null=True,
                verbose_name="JATS default article type",
            ),
        ),
    ]
