# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-05 12:13
from __future__ import unicode_literals

from django.db import migrations, models

def canonize_keywords(apps, schema_editor):
    map_kw_en = {}
    map_kw_de = {}

    Keyword = apps.get_model('submission', 'Keyword')
    KeywordArticle = apps.get_model('submission', 'KeywordArticle')

    for kw in Keyword.objects.all():
        if kw.language == 'en': m = map_kw_en
        if kw.language == 'de': m = map_kw_de
        if kw.word in m:
            h = m[kw.word]
        else:
            h = {}
            m[kw.word] = h
        h[kw.pk] = kw

    for kw_article in KeywordArticle.objects.all():
        kw = kw_article.keyword
        if kw.language == 'en': m = map_kw_en
        if kw.language == 'de': m = map_kw_de
        h = m[kw.word]
        id = sorted(h.keys())[0]
        kw_canon = h[id]
        if kw.pk != kw_canon.pk:
            kw_article.keyword = kw_canon            
            kw_article.save()

def remove_obsolete_keywords(apps, schema_editor):
    Keyword = apps.get_model('submission', 'Keyword')
    KeywordArticle = apps.get_model('submission', 'KeywordArticle')

    l = set()
    for kwa in KeywordArticle.objects.all():
        l.add(kwa.keyword.pk) 

    for kw in Keyword.objects.all():
        if kw.pk not in l:
            kw.delete()
                
class Migration(migrations.Migration):

    dependencies = [
        ('submission', '9004_tuw_add_lang_to_submission'),
    ]

    operations = [
        migrations.RunPython(canonize_keywords, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(remove_obsolete_keywords, reverse_code=migrations.RunPython.noop),
    ]
