# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-09 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '9005_tuw_clean_double_keywords'),
    ]

    operations = [
        migrations.RenameField('Article', 'title_de_tuw', 'title_de_tuw'),
        migrations.RenameField('Article', 'subtitle_de_tuw', 'subtitle_de_tuw'),
        migrations.RenameField('Article', 'abstract_de_tuw', 'abstract_de_tuw'),
    ]

    
