# Generated by Django 4.2.15 on 2024-09-19 13:36

import core.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0080_frozen_author_bleach_20240507_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract_de_tuw',
            field=core.model_utils.JanewayBleachField(blank=True, help_text='Abstract (German)', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='datacite_state',
            field=models.CharField(blank=True, choices=[('', ''), ('', 'draft'), ('findable', 'findable'), ('registered', 'registered')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=core.model_utils.JanewayBleachCharField(blank=True, help_text='Subtitle for the article.', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle_de_tuw',
            field=core.model_utils.JanewayBleachCharField(blank=True, help_text='Subtitle of the parallel title of the article', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_de_tuw',
            field=core.model_utils.JanewayBleachCharField(blank=True, db_column='title_de_tuw', help_text='Parallel title of the article', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='language',
            field=models.CharField(default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(max_length=200),
        ),
    ]
