# Generated by Django 4.2.16 on 2025-04-14 11:17

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0082_article_abstract_es_article_title_es_section_name_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subtitle_de',
            field=core.model_utils.JanewayBleachCharField(blank=True, help_text='Subtitle for the article.', max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='subtitle_en',
            field=core.model_utils.JanewayBleachCharField(blank=True, help_text='Subtitle for the article.', max_length=999, null=True),
        ),
    ]
