# Generated by Django 4.2.16 on 2025-04-14 12:01

from django.db import migrations

from submission import models as submission_models

def set_languages(apps, schema_editor):
    article: submission_models.Article

    l_english =  [
        #jfm
        113,120,126,133,139,
        #oes
        185,204,419,434,435,436,444,446,447,458,460,461,472,
    ]

    l_german =  [
        # jfm
        1,2,3,10,11,12,19,20,21,27,28,29,36,37,38,43,44,45,50,51,52,57,58,59,64,65,66,71,72,73,79,80,81,86,87,88,93,94,95,100,101,102,107,108,109,114,115,
        121,122,127,128,134,135,140,141,
        # oes
        145,146,147,155,156,161,162,167,168,169,171,172,173,178,179,186,187,188,194,195,196,197,
        205,206,211,212,213,214,215,217,218,219,224,225,226,231,232,233,234,235,237,238,239,243,
        244,245,246,249,250,251,252,253,256,257,258,263,264,265,270,271,272,273,274,279,280,281,
        286,287,288,289,295,296,297,298,303,304,305,310,318,319,320,321,322,326,327,328,329,330,
        334,335,336,337,346,347,348,349,350,355,356,357,358,362,363,364,365,369,370,371,379,380,
        381,382,383,384,389,390,391,392,403,404,405,406,420,421,422,429,432,433,445,457,459,473,
        474,475,486,487,488,489,490,506,507,508,509,510,520,521,522,523,539,
    ]

    articles = submission_models.Article.objects.all().order_by('id')
    for article in articles:
        print (f"processing article {article.pk}")

        # language corrections
        # hardcoded
        if not article.language:
            if article.pk in l_german:
                article.language = 'deu'
                print (f"setting language to {article.language}")
                article.save()

            elif article.pk in l_english:
                article.language = 'eng'
                print (f"setting language to {article.language}")
                article.save()

class Migration(migrations.Migration):

    dependencies = [
        ('submission', '9009_tuw_article_subtitle_en_article_subtitle_de'),
    ]

    operations = [
        migrations.RunPython(
            set_languages,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
