# Generated by Django 4.2.16 on 2025-04-17 12:26

from django.db import migrations

import core.model_utils

from submission import models as submission_models

class Migration(migrations.Migration):


    def set_state(apps, schema_editor):
        articles = submission_models.Article.objects.all()
        for article in articles:
            if article.get_doi() is not None:
                if article.datacite_state is None: article.datacite_state=submission_models.DATACITE_STATE_FINDABLE
                if article.datacite_ts is None: article.datacite_ts=datetime(2020,1,1)
                article.save()

    dependencies = [
        ('submission', '9010_tuw_set_missing_article_languages'),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name='article',
#            name='abstract_de_tuw',
#        ),
#        migrations.RemoveField(
#            model_name='article',
#            name='subtitle_de_tuw',
#        ),
#        migrations.RemoveField(
#            model_name='article',
#            name='title_de_tuw',
#        ),
        migrations.RunPython(set_state),
    ]
