# Generated by Django 4.2.16 on 2025-04-17 12:26

import core.model_utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '9010_tuw_set_missing_article_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='abstract_de_tuw',
        ),
        migrations.RemoveField(
            model_name='article',
            name='subtitle_de_tuw',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_de_tuw',
        ),
    ]
