# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-06 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '9000_tuw_add_visible_to_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='competing_interests',
            field=models.TextField(blank=True, help_text='If you have any conflict of interests in the publication of this article please state them here.', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='stage',
            field=models.CharField(choices=[('Unsubmitted', 'Unsubmitted'), ('Unassigned', 'Unassigned'), ('Assigned', 'Assigned to Editor'), ('Under Review', 'Peer Review'), ('Under Revision', 'Revision'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Editor Copyediting', 'Editor Copyediting'), ('Author Copyediting', 'Author Copyediting'), ('Final Copyediting', 'Final Copyediting'), ('Typesetting', 'Typesetting'), ('Proofing', 'Proofing'), ('pre_publication', 'Pre Publication'), ('Published', 'Published'), ('preprint_review', 'Preprint Review'), ('preprint_published', 'Preprint Published'), ('Back Content', 'Back Content Plugin')], default='Unsubmitted', max_length=200),
        ),
    ]
