# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-29 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_migrate_issue_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German')], help_text='Language for which this nav item is displayed, leave empty if item is to be shown regardless of language', max_length=200, null=True),
        ),
    ]
