# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-29 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_navitem_add_language'),
    ]

    operations = [
        migrations.RenameField('Page', 'display_name', 'display_name_tmp'),
        migrations.RenameField('Page', 'content', 'content_tmp'),
    ]
