# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-29 17:15
from __future__ import unicode_literals

from django.db import migrations


def translate(apps, schema_editor):
    Page = apps.get_model('cms', 'Page')
    PageTranslation = apps.get_model('cms', 'PageTranslation')
    for instance in Page.objects.all():
        PageTranslation.objects.create(
            master=instance,
            language_code='en',
            display_name=instance.display_name_tmp,
            content=instance.content_tmp,
        )

def untranslate(apps, schema_editor):
    Page = apps.get_model('cms', 'Page')
    PageTranslation = apps.get_model('cms', 'PagelTranslation')
    for obj in PageTranslation.objects.filter(language_code='en').select_related('master'):
        obj.master.display_name_tmp = obj.display_name
        obj.master.content_tmp = obj.content
        obj.master.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_page_translatable'),
    ]

    operations = [
        migrations.RunPython(translate,reverse_code = untranslate)        
    ]


