# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-29 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '9004_TUW_auto_20191229_1828'),
    ]

    operations = [
        migrations.RenameField('NavigationItem', 'link_name', 'link_name_tmp'),
    ]        
