# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-29 20:39
from __future__ import unicode_literals

from django.db import migrations


def translate(apps, schema_editor):
    NavigationItem = apps.get_model('cms', 'NavigationItem')
    NavigationItemTranslation = apps.get_model('cms', 'NavigationItemTranslation')
    for instance in NavigationItem.objects.all():
        NavigationItemTranslation.objects.create(
            master=instance,
            language_code='en',
            link_name=instance.link_name_tmp,
        )

def untranslate(apps, schema_editor):
    NavigationItem = apps.get_model('cms', 'NavigationItem')
    NavigationItemTranslation = apps.get_model('cms', 'NavigationItemTranslation')
    for obj in NavigationItemTranslation.objects.filter(language_code='en').select_related('master'):
        obj.master.link_name_tmp = obj.link_name
        obj.master.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cms', '9006_auto_20191229_2138'),
    ]

    operations = [
        migrations.RunPython(translate,reverse_code=untranslate)        
    ]
