# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-29 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '9007_auto_20191229_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationitem',
            name='link_name_tmp',
        ),
    ]
